name: edukit
description: "A new Flutter project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^8.3.1
  go_router: ^14.7.2
  flutter_bloc: ^9.0.0
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  flutter_svg: ^2.0.17
  hydrated_bloc: ^10.0.0
  google_fonts: ^6.2.1
  repositories:
    path: packages/repositories

  app_foundation:
    path: packages/app_foundation

  bloc_suite:
    git:
      url: https://github.com/rahulsharmadev0/suite.git
      ref: main
      path: packages/bloc_suite

  dart_suite:
    git:
      url: https://github.com/rahulsharmadev0/suite.git
      ref: main
      path: packages/dart_suite

  uuid: ^4.5.1
  collection: ^1.19.0
  equatable: ^2.0.7
  freezed_annotation: ^2.4.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8

flutter:
  uses-material-design: true
