name: edukit
description: "A new Flutter project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^9.0.2
  go_router: ^14.8.1
  flutter_bloc: ^9.0.0
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  flutter_svg: ^2.0.17
  hydrated_bloc: ^10.0.0
  google_fonts: ^6.2.1

  bloc_suite: ^0.0.5
  dart_suite: ^0.0.2

  repositories:
    path: packages/repositories

  app_foundation:
    path: packages/app_foundation

  uuid: ^4.5.1
  collection: ^1.19.0
  equatable: ^2.0.7
  freezed_annotation: ^3.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  go_router_builder: ^2.8.1
  flutter_lints: ^5.0.0
  freezed: ^3.0.2

flutter:
  uses-material-design: true
